In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer
from sklearn.decomposition import NMF
import pickle

In [2]:
ratings = pd.read_csv('ratings.csv')
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [3]:
movies=pd.read_csv('movies.csv')
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [4]:
df=pd.merge(ratings,movies,on='movieId')

In [5]:
df

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,1106635946,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,1510577970,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,1305696483,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...,...
100831,610,160341,2.5,1479545749,Bloodmoon (1997),Action|Thriller
100832,610,160527,4.5,1479544998,Sympathy for the Underdog (1971),Action|Crime|Drama
100833,610,160836,3.0,1493844794,Hazard (2005),Action|Drama|Thriller
100834,610,163937,3.5,1493848789,Blair Witch (2016),Horror|Thriller
100835,610,163981,3.5,1493850155,31 (2016),Horror

In [6]:
df.drop(columns=["timestamp"],inplace=True)

In [7]:
df

,userId,movieId,rating,title,genres
0,1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...
100831,610,160341,2.5,Bloodmoon (1997),Action|Thriller
100832,610,160527,4.5,Sympathy for the Underdog (1971),Action|Crime|Drama
100833,610,160836,3.0,Hazard (2005),Action|Drama|Thriller
100834,610,163937,3.5,Blair Witch (2016),Horror|Thriller
100835,610,163981,3.5,31 (2016),Horror

In [8]:
df.set_index('userId')

,movieId,rating,title,genres
userId,,,,
1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
5,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
7,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
15,1,2.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
17,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...
610,160341,2.5,Bloodmoon (1997),Action|Thriller
610,160527,4.5,Sympathy for the Underdog (1971),Action|Crime|Drama
610,160836,3.0,Hazard (2005),Action|Drama|Thriller
610,163937,3.5,Blair Witch (2016),Horror|Thriller
610,163981,3.5,31 (2016),Horror

In [9]:
df

,userId,movieId,rating,title,genres
0,1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...
100831,610,160341,2.5,Bloodmoon (1997),Action|Thriller
100832,610,160527,4.5,Sympathy for the Underdog (1971),Action|Crime|Drama
100833,610,160836,3.0,Hazard (2005),Action|Drama|Thriller
100834,610,163937,3.5,Blair Witch (2016),Horror|Thriller
100835,610,163981,3.5,31 (2016),Horror

In [10]:
df[df['title']=='\'Hellboy\': The Seeds of Creation (2004)']

,userId,movieId,rating,title,genres
97100,332,97757,4.0,'Hellboy': The Seeds of Creation (2004),Action|Adventure|Comedy|Documentary|Fantasy

In [11]:
df2=pd.pivot_table(df,index='userId',columns='title',values='rating')

In [12]:
df2

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [13]:
df2.isna().sum()

title
'71 (2014)                                   609
'Hellboy': The Seeds of Creation (2004)      609
'Round Midnight (1986)                       608
'Salem's Lot (2004)                          609
'Til There Was You (1997)                    608
                                            ...
eXistenZ (1999)                              588
xXx (2002)                                   586
xXx: State of the Union (2005)               605
¡Three Amigos! (1986)                        584
À nous la liberté (Freedom for Us) (1931)    609
Length: 9719, dtype: int64

In [14]:
imputer=KNNImputer(n_neighbors=2)

In [15]:
dfrecs=pd.DataFrame(imputer.fit_transform(df2), 
                       index = df2.index, 
                       columns = df2.columns)

In [16]:
dfrecs

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,4.0,3.5,5.0,4.0,1.5,4.00,3.0,4.50,3.75,...,1.5,4.00,3.25,3.0,3.0,3.75,2.00,2.00,4.00,1.0
2,4.0,4.0,3.5,5.0,4.0,1.5,4.25,3.0,4.50,3.00,...,1.5,4.00,3.25,3.0,3.0,4.00,2.25,1.75,2.00,1.0
3,4.0,4.0,3.5,5.0,4.0,1.5,2.50,3.0,3.00,2.75,...,1.5,4.50,3.25,3.0,3.0,2.75,3.25,1.75,2.50,1.0
4,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.25,3.25,...,1.5,3.25,3.25,3.0,3.0,3.50,2.25,2.25,3.00,1.0
5,4.0,4.0,3.5,5.0,4.0,1.5,2.50,3.0,4.50,3.25,...,1.5,4.25,4.00,3.0,3.0,4.50,3.50,1.75,3.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.25,3.75,...,1.5,3.25,3.25,3.0,3.0,4.25,3.75,2.25,3.25,1.0
607,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.25,3.75,...,1.5,4.00,4.00,3.0,3.0,4.25,3.50,2.25,3.75,1.0
608,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.75,3.25,...,1.5,4.00,4.00,3.0,3.0,4.50,3.50,2.00,3.25,1.0
609,4.0,4.0,3.5,5.0,4.0,1.5,3.50,3.0,3.25,3.00,...,1.5,4.25,3.75,3.0,3.0,4.00,3.00,2.25,4.25,1.0
610,4.0,4.0,3.5,5.0,4.0,1.5,3.25,3.0,3.50,3.25,...,1.5,4.00,3.50,3.0,3.0,3.25,2.00,1.50,3.25,1.0

In [17]:
#dfrecs.to_csv('Movie_recommender.csv', index=True)

###### Create a model

In [18]:
model=NMF(n_components=20,init='random',random_state=42,max_iter=10000)
model.fit(dfrecs)

C:\Users\bened\anaconda3\lib\site-packages\sklearn\decomposition\_nmf.py:1090: ConvergenceWarning: Maximum number of iterations 10 reached. Increase it to improve convergence.
  warnings.warn("Maximum number of iterations %d reached. Increase it to"

NMF(init='random', max_iter=10, n_components=20, random_state=42)

In [19]:
model.components_

array([[0.78992221, 0.71581174, 0.33066931, ..., 0.        , 0.17181733,
        0.12256178],
       [0.22976732, 0.10203409, 0.09484944, ..., 0.        , 0.93974047,
        0.06587352],
       [0.30466872, 0.68488851, 0.75285088, ..., 0.433359  , 0.47177358,
        0.06766236],
       ...,
       [0.43930519, 0.40312372, 0.29301753, ..., 0.05147923, 0.411769  ,
        0.37384819],
       [0.03700137, 0.        , 0.21725003, ..., 0.57694708, 0.        ,
        0.56239873],
       [0.33418598, 0.24824881, 0.48747497, ..., 0.3345332 , 0.31534159,
        0.18168477]])

In [20]:
Q=pd.DataFrame(model.components_,
              columns=dfrecs.columns,
              index=['feature1','feature2','feature3','feature4','feature5','feature6','feature7','feature8','feature9','feature10',
                    'feature11','feature12','feature13','feature14','feature15','feature16','feature17','feature18','feature19','feature20'])

In [21]:
Q

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
feature1,0.789922,0.715812,0.330669,1.124687,0.875426,0.101472,0.570961,0.356929,0.283342,0.429190,...,0.108834,0.369708,0.183566,0.339546,0.000000,0.436945,0.307921,0.000000,0.171817,0.122562
feature2,0.229767,0.102034,0.094849,0.053337,0.020841,0.055119,0.150514,0.022662,0.569924,0.202248,...,0.093552,0.694773,0.762485,0.030808,0.170189,0.164032,0.073994,0.000000,0.939740,0.065874
feature3,0.304669,0.684889,0.752851,0.250651,0.408750,0.062475,0.211128,0.257996,0.082253,0.391731,...,0.059128,0.251976,0.195260,0.101004,0.553426,0.000000,0.277256,0.433359,0.471774,0.067662
feature4,0.543700,0.312927,0.089845,0.289666,0.335715,0.018372,0.000000,0.593555,0.626887,0.350566,...,0.007207,0.581029,0.285676,0.161031,0.003527,0.551572,0.119790,0.033419,0.503424,0.039712
feature5,0.452638,0.653388,0.315004,0.371787,0.201100,0.025431,0.547575,0.444591,0.300655,0.290266,...,0.077356,0.172194,0.409375,0.154314,0.136352,1.224731,0.388305,0.191066,0.430844,0.000000
feature6,0.389083,0.409791,0.584537,0.645526,0.183991,0.306973,0.094282,0.486924,0.352897,0.130938,...,0.204604,0.633292,0.485394,0.361869,0.215543,0.338117,0.772499,0.324931,0.000000,0.234108
feature7,0.299426,0.490371,0.416413,0.527498,0.272375,0.000000,0.458326,0.000000,0.516304,0.587588,...,0.000000,0.848093,0.242166,0.065378,0.000608,0.000000,0.208765,0.038218,0.560593,0.000000
feature8,0.164462,0.038111,0.381661,0.230929,0.252818,0.102847,0.788999,0.138414,0.332911,0.114173,...,0.029735,0.223726,0.173265,0.388663,0.847719,0.000000,0.000000,0.372480,0.000000,0.000000
feature9,0.513461,0.639858,0.315195,0.616382,0.471030,0.026635,0.137979,0.379718,0.034545,0.266931,...,0.000000,0.000000,0.567579,0.617201,0.367063,0.509476,0.504066,0.381324,0.447549,0.011766
feature10,0.014927,0.093622,0.444882,0.370916,0.078515,0.180186,0.266306,0.049926,0.171312,0.520465,...,0.000000,0.153054,0.412916,0.560815,0.510068,0.441712,0.798239,0.410001,0.052323,0.000000
feature11,0.372816,0.346368,0.191023,0.333102,0.285502,0.049270,0.421473,0.101832,0.534971,0.472246,...,0.000000,0.526288,0.469780,0.068612,0.104808,0.271783,0.038464,0.100059,0.496833,0.068298
feature12,0.080713,0.109213,0.331347,0.356704,0.355933,0.334393,0.029160,0.267368,0.632038,0.476279,...,0.273449,0.431314,0.640681,0.562326,0.597947,0.392410,0.298560,0.212800,0.116788,0.000000
feature13,0.144573,0.334755,0.545139,0.252543,0.121542,0.246833,0.623955,0.596394,0.010837,0.209539,...,0.159088,0.216217,0.395674,0.211116,0.264774,0.319253,0.633268,0.419389,0.369874,0.000000
feature14,0.247637,0.380734,0.543897,0.318049,0.199828,0.231894,0.000000,0.341051,0.343209,0.198385,...,0.355119,0.270000,0.651725,0.335587,0.712134,0.608638,0.000000,0.429473,0.274415,0.000000
feature15,0.409471,0.251040,0.466627,0.319180,0.553192,0.244282,0.590381,0.047179,0.599074,0.347431,...,0.388558,0.335480,0.450527,0.213153,0.663472,0.696429,0.312791,0.329817,0.658070,0.000000
feature16,0.078007,0.085560,0.252411,0.138440,0.074042,0.348731,0.308193,0.398838,1.005579,0.307351,...,0.390180,0.140709,0.086492,0.814336,0.857822,0.251572,0.143880,0.863592,0.000000,0.007497
feature17,0.253798,0.314077,0.403213,0.501998,0.000293,0.066725,0.143033,0.303831,1.129221,0.334593,...,0.125851,0.000000,0.176612,0.291880,0.614541,0.606075,0.754220,0.340486,0.000000,0.178681
feature18,0.439305,0.403124,0.293018,0.547987,0.335440,0.126874,0.377758,0.337234,0.000000,0.022272,...,0.228526,0.898340,0.400454,0.231898,0.417353,0.255559,0.000000,0.051479,0.411769,0.373848
feature19,0.037001,0.000000,0.217250,0.080816,0.413898,0.595059,0.322280,0.450780,0.526455,0.587487,...,0.767439,0.079259,0.185871,0.559590,0.771718,0.528764,0.035362,0.576947,0.000000,0.562399
feature20,0.334186,0.248249,0.487475,0.200141,0.514985,0.406889,0.370247,0.582065,0.128634,0.288549,...,0.157878,0.597585,0.492575,0.434378,0.189476,0.249893,0.391689,0.334533,0.315342,0.181685

In [22]:
P=pd.DataFrame(model.transform(dfrecs),index=dfrecs.index,
                 columns=['feature1','feature2','feature3','feature4','feature5','feature6','feature7','feature8','feature9','feature10',
                         'feature11','feature12','feature13','feature14','feature15','feature16','feature17','feature18','feature19','feature20'])

C:\Users\bened\anaconda3\lib\site-packages\sklearn\decomposition\_nmf.py:1090: ConvergenceWarning: Maximum number of iterations 10 reached. Increase it to improve convergence.
  warnings.warn("Maximum number of iterations %d reached. Increase it to"

In [23]:
P

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,feature12,feature13,feature14,feature15,feature16,feature17,feature18,feature19,feature20
userId,,,,,,,,,,,,,,,,,,,,
1,2.842817,1.849906,1.207710,0.843713,0.495312,0.085324,0.092976,0.618376,0.000000,0.712713,0.010730,0.217212,0.393320,0.100250,0.000000,0.554120,0.054062,0.000000,0.483502,0.0
2,2.687719,1.761067,1.226418,0.654127,0.432375,0.672538,0.000000,0.556389,0.001055,0.613909,0.000000,0.565895,0.222382,0.016146,0.000000,0.374491,0.076862,0.000000,0.417696,0.0
3,2.448658,1.528954,1.216269,0.674340,0.346703,1.284823,0.000000,0.458877,0.019936,0.531152,0.000000,0.796662,0.050558,0.000000,0.075462,0.153742,0.000000,0.042809,0.259003,0.0
4,2.556805,1.623170,1.277760,0.579409,0.588163,0.821500,0.000000,0.734515,0.045042,0.248180,0.000000,0.783119,0.000000,0.125557,0.000000,0.312627,0.000000,0.034954,0.267818,0.0
5,2.599333,1.625522,1.254477,0.623131,0.613755,0.891227,0.000000,0.761099,0.000000,0.331328,0.000000,0.609238,0.005531,0.133918,0.000000,0.245052,0.000000,0.003514,0.371118,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.544089,1.572715,1.219922,0.624813,0.673527,0.608831,0.008206,0.457804,0.094690,0.259119,0.121863,0.552807,0.025589,0.254704,0.000000,0.465759,0.380013,0.000000,0.347184,0.0
607,2.772413,1.837955,1.263770,0.619577,0.694964,0.215397,0.003640,0.486295,0.009324,0.621436,0.000000,0.573731,0.197729,0.000000,0.027648,0.410389,0.102493,0.000000,0.487875,0.0
608,2.578197,1.601006,1.244423,0.710661,0.415228,0.864991,0.005274,0.297161,0.129245,0.428288,0.023865,0.573401,0.050010,0.000000,0.053187,0.288919,0.236655,0.000000,0.570876,0.0
609,2.529619,1.651935,1.291349,0.518424,0.632102,1.040584,0.000000,0.696318,0.013116,0.266980,0.000000,0.718722,0.034791,0.037691,0.060366,0.220695,0.000000,0.000000,0.315184,0.0
610,2.693647,1.684884,1.190358,0.796714,0.548622,0.412701,0.035582,0.498778,0.000000,0.613023,0.071844,0.319363,0.193431,0.170849,0.000000,0.455297,0.303249,0.000000,0.430317,0.0

In [24]:
recom_df=pd.DataFrame(np.dot(P,Q),index=dfrecs.index,columns=dfrecs.columns)

In [25]:
recom_df

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.072960,4.070987,3.507890,4.893684,4.046432,1.390244,3.746733,3.035229,4.097533,3.697516,...,1.385748,3.924155,3.589859,3.010675,3.148136,3.663814,2.746668,2.231229,3.727890,0.891945
2,3.961617,3.984283,3.586767,4.952732,3.942864,1.475897,3.377650,2.982114,3.982815,3.521877,...,1.394297,4.007434,3.701117,2.999066,3.069431,3.517245,2.990714,2.125017,3.396290,0.963291
3,3.916110,3.939110,3.643294,4.995974,3.836636,1.478255,2.948594,2.939277,3.730295,3.292658,...,1.313405,4.183650,3.764137,2.871747,2.816594,3.364366,3.171062,1.929664,3.135941,0.973747
4,3.974387,4.027406,3.558958,4.892051,3.934300,1.391793,3.243972,2.925017,3.866614,3.284736,...,1.339501,4.023755,3.691217,2.876081,3.055607,3.446612,2.703138,1.991792,3.286020,0.888638
5,4.019974,4.048684,3.587523,4.934375,3.954409,1.413233,3.320152,2.964924,3.838798,3.319737,...,1.362352,4.026778,3.663458,2.855308,3.022284,3.526603,2.768178,2.006058,3.272870,0.955795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,4.056810,4.175805,3.561440,4.948457,3.862586,1.383469,3.213333,3.057521,4.313399,3.450343,...,1.432617,3.824188,3.655646,2.937179,3.155564,3.851980,2.852807,2.171117,3.360323,0.941382
607,3.989986,4.061392,3.471221,4.871361,4.022306,1.406678,3.534179,2.928112,4.047486,3.658729,...,1.411684,3.839353,3.672731,2.961479,3.093502,3.788685,2.810814,2.095683,3.608157,0.917286
608,4.005576,4.046045,3.527410,4.972533,3.955500,1.502433,3.049701,3.049321,4.066295,3.511864,...,1.493058,3.922227,3.628055,2.947540,2.952270,3.639639,3.040732,2.081576,3.286788,1.105039
609,3.995258,4.063826,3.637924,4.934068,3.920325,1.430444,3.280025,2.942326,3.816293,3.280126,...,1.359358,4.078015,3.730040,2.819391,2.977800,3.493126,2.888711,1.985730,3.296285,0.949494
610,4.072716,4.109832,3.558818,4.971310,3.921156,1.390372,3.437963,3.058175,4.248695,3.607313,...,1.393451,3.882432,3.611435,2.971795,3.128003,3.811483,2.938233,2.194245,3.488647,0.954440

In [26]:
a=dfrecs-recom_df
a

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,-0.072960,-0.070987,-0.007890,0.106316,-0.046432,0.109756,0.253267,-0.035229,0.402467,0.052484,...,0.114252,0.075845,-0.339859,-0.010675,-0.148136,0.086186,-0.746668,-0.231229,0.272110,0.108055
2,0.038383,0.015717,-0.086767,0.047268,0.057136,0.024103,0.872350,0.017886,0.517185,-0.521877,...,0.105703,-0.007434,-0.451117,0.000934,-0.069431,0.482755,-0.740714,-0.375017,-1.396290,0.036709
3,0.083890,0.060890,-0.143294,0.004026,0.163364,0.021745,-0.448594,0.060723,-0.730295,-0.542658,...,0.186595,0.316350,-0.514137,0.128253,0.183406,-0.614366,0.078938,-0.179664,-0.635941,0.026253
4,0.025613,-0.027406,-0.058958,0.107949,0.065700,0.108207,0.506028,0.074983,0.383386,-0.034736,...,0.160499,-0.773755,-0.441217,0.123919,-0.055607,0.053388,-0.453138,0.258208,-0.286020,0.111362
5,-0.019974,-0.048684,-0.087523,0.065625,0.045591,0.086767,-0.820152,0.035076,0.661202,-0.069737,...,0.137648,0.223222,0.336542,0.144692,-0.022284,0.973397,0.731822,-0.256058,-0.272870,0.044205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,-0.056810,-0.175805,-0.061440,0.051543,0.137414,0.116531,0.536667,-0.057521,-0.063399,0.299657,...,0.067383,-0.574188,-0.405646,0.062821,-0.155564,0.398020,0.897193,0.078883,-0.110323,0.058618
607,0.010014,-0.061392,0.028779,0.128639,-0.022306,0.093322,0.215821,0.071888,0.202514,0.091271,...,0.088316,0.160647,0.327269,0.038521,-0.093502,0.461315,0.689186,0.154317,0.141843,0.082714
608,-0.005576,-0.046045,-0.027410,0.027467,0.044500,-0.002433,0.700299,-0.049321,0.683705,-0.261864,...,0.006942,0.077773,0.371945,0.052460,0.047730,0.860361,0.459268,-0.081576,-0.036788,-0.105039
609,0.004742,-0.063826,-0.137924,0.065932,0.079675,0.069556,0.219975,0.057674,-0.566293,-0.280126,...,0.140642,0.171985,0.019960,0.180609,0.022200,0.506874,0.111289,0.264270,0.953715,0.050506
610,-0.072716,-0.109832,-0.058818,0.028690,0.078844,0.109628,-0.187963,-0.058175,-0.748695,-0.357313,...,0.106549,0.117568,-0.111435,0.028205,-0.128003,-0.561483,-0.938233,-0.694245,-0.238647,0.045560

In [27]:
model.reconstruction_err_

849.2855397348056

###### Save modell

In [ ]:
binary = pickle.dumps(model)
open('modelone.bin', 'wb').write(binary)

In [ ]:
binary = open('modelone.bin', 'rb').read()
model_read = pickle.loads(binary)

Create new customer

In [28]:
BK = np.zeros(shape= (1,len(recom_df.columns))).tolist()[0]
BK

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [29]:
BK_ratings = {'xXx (2002)': 4,'¡Three Amigos! (1986)':3}
BK_ratings

{'xXx (2002)': 4, '¡Three Amigos! (1986)': 3}

In [30]:
for index,item in enumerate (dfrecs.columns):
    if item in BK_ratings.keys():
        print(index,item)
        BK[index]=BK_ratings[item]

9715 xXx (2002)
9717 ¡Three Amigos! (1986)

In [31]:
BKdf=pd.DataFrame([BK],index = ['BK'],columns= dfrecs.columns)

In [32]:
BKdf

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
BK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4,0.0,3,0.0

###### add new customer (BK) to the dfrecs

In [33]:
dfrecsnew=pd.concat([dfrecs,BKdf])

In [34]:
dfrecsnew

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
1,4.0,4.0,3.5,5.0,4.0,1.5,4.00,3.0,4.50,3.75,...,1.5,4.00,3.25,3.0,3.0,3.75,2.00,2.00,4.00,1.0
2,4.0,4.0,3.5,5.0,4.0,1.5,4.25,3.0,4.50,3.00,...,1.5,4.00,3.25,3.0,3.0,4.00,2.25,1.75,2.00,1.0
3,4.0,4.0,3.5,5.0,4.0,1.5,2.50,3.0,3.00,2.75,...,1.5,4.50,3.25,3.0,3.0,2.75,3.25,1.75,2.50,1.0
4,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.25,3.25,...,1.5,3.25,3.25,3.0,3.0,3.50,2.25,2.25,3.00,1.0
5,4.0,4.0,3.5,5.0,4.0,1.5,2.50,3.0,4.50,3.25,...,1.5,4.25,4.00,3.0,3.0,4.50,3.50,1.75,3.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.25,3.75,...,1.5,4.00,4.00,3.0,3.0,4.25,3.50,2.25,3.75,1.0
608,4.0,4.0,3.5,5.0,4.0,1.5,3.75,3.0,4.75,3.25,...,1.5,4.00,4.00,3.0,3.0,4.50,3.50,2.00,3.25,1.0
609,4.0,4.0,3.5,5.0,4.0,1.5,3.50,3.0,3.25,3.00,...,1.5,4.25,3.75,3.0,3.0,4.00,3.00,2.25,4.25,1.0
610,4.0,4.0,3.5,5.0,4.0,1.5,3.25,3.0,3.50,3.25,...,1.5,4.00,3.50,3.0,3.0,3.25,2.00,1.50,3.25,1.0
BK,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.00,4.00,0.00,3.00,0.0

run the model again with new customer

In [35]:
P_BK = model.transform(BKdf)

C:\Users\bened\anaconda3\lib\site-packages\sklearn\decomposition\_nmf.py:1090: ConvergenceWarning: Maximum number of iterations 10 reached. Increase it to improve convergence.
  warnings.warn("Maximum number of iterations %d reached. Increase it to"

In [36]:
R_BK = np.dot(P_BK, Q)
RecomBK = pd.DataFrame(R_BK,index=['BK'],
                                columns=dfrecs.columns)

In [37]:
RecomBK

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
BK,0.000757,0.000873,0.001327,0.000923,0.000541,0.000614,0.001258,0.001024,0.000916,0.000812,...,0.000497,0.001268,0.001706,0.000767,0.001015,0.001135,0.001566,0.000945,0.001599,0.000144

In [43]:
recom_dfnew=pd.concat([recom_df,RecomBK])

In [58]:
top10=recom_dfnew.loc['BK'].sort_values(ascending=False).head(10)

In [59]:
top10

title
47 Ronin (2013)                    0.002595
Kung Pow: Enter the Fist (2002)    0.002574
Coyote Ugly (2000)                 0.002565
Relic, The (1997)                  0.002514
The Scorpion King (2002)           0.002506
Island, The (2005)                 0.002504
Tomorrowland (2015)                0.002473
Air Force One (1997)               0.002468
Just Go with It (2011)             0.002440
Taken 2 (2012)                     0.002405
Name: BK, dtype: float64

In [60]:
top10=top10.index.to_list()

In [61]:
top10

['47 Ronin (2013)',
 'Kung Pow: Enter the Fist (2002)',
 'Coyote Ugly (2000)',
 'Relic, The (1997)',
 'The Scorpion King (2002)',
 'Island, The (2005)',
 'Tomorrowland (2015)',
 'Air Force One (1997)',
 'Just Go with It (2011)',
 'Taken 2 (2012)']